# Open-WebUI OAuth Configuration for Authentik SSO
# This file configures Open-WebUI to use Authentik for authentication

version: '3.8'

services:
  open-webui:
    environment:
      # Enable OAuth authentication
      ENABLE_OAUTH_SIGNUP: "true"
      OAUTH_MERGE_ACCOUNTS_BY_EMAIL: "true"
      
      # OpenID Connect Configuration
      OPENID_PROVIDER_URL: "http://authentik-server:9000/application/o/open-webui/"
      OPENID_CLIENT_ID: "open-webui"
      OPENID_CLIENT_SECRET: "${OPENWEBUI_OAUTH_CLIENT_SECRET}"
      OPENID_REDIRECT_URI: "http://localhost:8080/oauth/oidc/callback"
      OPENID_SCOPE: "openid profile email groups"
      
      # Provider display settings
      OPENID_PROVIDER_DISPLAY_NAME: "UC-1 Pro SSO"
      OPENID_PROVIDER_LOGO_URL: "http://authentik-server:9000/static/dist/assets/icons/icon.svg"
      
      # Disable local registration when using SSO
      ENABLE_SIGNUP: "false"
      
      # Auto-redirect to SSO login
      DEFAULT_AUTH_PROVIDER: "oidc"
      
      # User role mapping from Authentik groups
      OPENID_GROUP_CLAIM: "groups"
      OPENID_ADMIN_GROUP: "uc1-admins"
      OPENID_MODERATOR_GROUP: "uc1-developers"
      
      # Session configuration
      SESSION_COOKIE_SECURE: "false"  # Set to true in production with HTTPS
      SESSION_COOKIE_SAMESITE: "lax"
      SESSION_COOKIE_NAME: "open-webui-session"