# Traefik Middleware Configuration for Authentik SSO
# This file defines authentication middleware for UC-1 Pro services

http:
  middlewares:
    # Main Authentik ForwardAuth middleware
    authentik:
      forwardAuth:
        address: "http://authentik-proxy:9876/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version
    
    # Admin-only middleware (requires uc1-admins group)
    authentik-admin:
      forwardAuth:
        address: "http://authentik-proxy:9876/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
        authResponseHeadersRegex: "^X-authentik-groups: .*uc1-admins.*"
    
    # Developer middleware (requires uc1-developers or uc1-admins group)
    authentik-developer:
      forwardAuth:
        address: "http://authentik-proxy:9876/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
        authResponseHeadersRegex: "^X-authentik-groups: .*(uc1-developers|uc1-admins).*"
    
    # User middleware (any authenticated user)
    authentik-user:
      forwardAuth:
        address: "http://authentik-proxy:9876/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
    
    # Rate limiting middleware
    rate-limit:
      rateLimit:
        average: 100
        burst: 200
        period: 1m
    
    # Security headers middleware
    security-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        sslRedirect: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
    
    # CORS middleware for API services
    cors:
      headers:
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-Requested-With"
        accessControlAllowOriginList:
          - "http://localhost:8080"
          - "http://localhost:8084"
          - "https://*.localhost"
        accessControlMaxAge: 100
        addVaryHeader: true
    
    # Redirect to HTTPS (for production)
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true