version: '3.8'

services:
  n8n:
    image: n8n/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Los_Angeles # Adjust to your timezone
      # For persistent data, uncomment the volume below
      # - ./data:/home/node/.n8n
    networks:
      - unicorn-network

networks:
  unicorn-network:
    external: true
